---
- hosts: localhost
  connection: local
  tasks:
    - name: Install Docker Dependencies
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - gnupg=2.2.27-3ubuntu2.1
        - ca-certificates=20211016
        - curl=7.81.0-1ubuntu1.6
        - lsb-release=11.1.0ubuntu4
      tags:
        - docker

    - name: Add Docker's GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
      tags:
        - docker

    - name: Update apt cache
      apt:
        update_cache: yes
      tags:
        - docker

    - name: Install Docker & Compose Plugin
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items: 
        - docker-ce=5:20.10.21~3-0~ubuntu-focal
        - docker-ce-cli=5:20.10.21~3-0~ubuntu-focal
        - containerd.io=1.6.9-1
        - docker-compose-plugin=2.12.2~ubuntu-focal
      tags:
        - docker
